In [9]:
#Numpy

# import numpy as np

# arr=np.array([1,2,3])    #Rank=1

# print(arr)

# arr=np.array([[2,4,6],   #Rank=2
#              [8,10,12]])   #If you miss "[]" or "()":TypeError: Field elements must be 2- or 3-tuples, got '8' 

# print(arr)

[1 2 3]
[[ 2  4  6]
 [ 8 10 12]]


In [15]:
#Numpy Indexing

#Accessing all the elements by index

# import numpy as np

# arr=np.array([[-2,6,8],       #Rank=2
#               [-9,1.5,7]])
# print(arr)

# print(arr[0,0])  #arr[Rows,Columns]
# print(arr[0,1])
# print(arr[0,2])
# print(arr[1,0])
# print(arr[1,1])
# print(arr[1,2])  

# print(arr[0:1]) #First Row

# print(arr[1:2]) #Second Row

# import numpy as np

# arr = np.array([[-1, 2, 0, 4],
#                 [4, -0.5, 6, 0],
#                 [2.6, 0, 7, 8],
#                 [3, -7, 4, 2.0]])

# Second Column
# print(*arr[0:,1])

# Fourth Column
# print(*arr[0:,3])

# Third row
# print(*arr[2:3,0:])

# Fourth Row
# print(*arr[3,0:4])


3.0 -7.0 4.0 2.0


In [21]:
# import numpy as np

# data=np.random.randint(0,50,(4,4))

# data


array([[19, 10,  1,  3],
       [ 4, 25, 23, 17],
       [13, 15, 39, 46],
       [22, 24, 13, 41]], dtype=int32)

In [ ]:
# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]

# import numpy as np

# retail_data = np.array([
#     [1, 25000, 300, 1200, 10],
#     [2, 32000, 450, 1500, 15],
#     [3, 28000, 380, 1100, 8],
#     [4, 41000, 500, 1600, 20],
#     [5, 35000, 420, 1400, 12],
#     [6, 27000, 360, 1300, 9],
#     [7, 39000, 480, 1700, 18],
#     [8, 30000, 400, 1250, 14],
#     [9, 45000, 550, 1800, 25],
#     [10, 33000, 410, 1450, 11]
# ])

# print(retail_data)

In [ ]:
# Retail Data – Business Questions (for `retail_data`)

# **Assumed columns:** `[StoreID, Sales, Customers, Inventory, Returns]`

## Basic Performance Analysis

# Question 1. What is the **total revenue** generated across all stores?


In [ ]:
# Question 2. Which store recorded the **highest sales**?

In [ ]:
# Question 3. Which store recorded the **lowest sales**?



In [ ]:
# Question 4. What is the **average daily sales** per store?

In [ ]:
# Question 5. How many stores achieved sales **above ₹35,000**?

In [ ]:
# Customer Insights

# Question 6. Which store had the **highest customer footfall**?


In [ ]:
# Question 7. What is the **average number of customers** per store?


In [ ]:
# Question 8. How many stores have **more than 450 customers**?

In [ ]:
# Question 9. Which store has the **lowest customer count**?

In [ ]:
# Question 10. Is there any store where **high sales do not correspond to high customers**?

In [ ]:
# Inventory & Returns Analysis

# Question 11. What is the **total inventory** across all stores?


In [ ]:
# Question 12. Which store has the **highest inventory stock**?


In [ ]:
# Question 13. How many stores have **inventory less than 1300 units**?


In [ ]:
# Question 14. Which store has the **highest return rate** (returns ÷ inventory)?


In [ ]:
# Question 15. Which stores have **returns greater than 15 units**?

In [ ]:
# Sales & Customer Correlation

# Question 16. Is there a **positive correlation** between sales and customers?


In [ ]:
# Question 17. Which store has **high customer visits but low sales**?


In [ ]:
# Question 18. Which store has **low customers but high sales**?


In [ ]:
# Question 19. How many stores have **sales per customer above ₹90**?


In [ ]:
# Question 20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?

In [ ]:
# Profitability & Growth

# Question 21. If profit margin is **20% of sales**, what is the **profit per store**?



In [ ]:
# Question 22. Which store has the **highest profit**?


In [ ]:
# Question 23. Which store has the **lowest profit**?


In [ ]:
# Question 24. If sales increase by **10% next month**, what are the **new sales figures**?


In [ ]:
# Question 25. How will **total profit** change with the 10% sales increase?

In [ ]:
# Operational Strategy

# Question 26. Which stores need **inventory restocking** based on sales and current stock?


In [ ]:
# Question 27. Which stores show **high returns percentage** and might require **quality checks**?


In [ ]:
# Question 28. Which store is the **best performer overall** (sales, customers, inventory turnover)?


In [ ]:
# Question 29. Which store is the **worst performer overall**?


In [ ]:
# Question 30. Which stores can be considered for **expansion** based on strong sales and customer metrics?
