Array Creation and Manipulation

In [115]:
#Question 1: Create a 4x4 identity matrix using np.eye()

# Identity matrices:
# For matrices, the n X n identity matrix is the matrix that has
# 1's on the main diagonal and O's elsewhere.

# import numpy as np

# np.eye(4,k=0)        # K=0: Main Diagonal,k=1(Incremental) and k=-1(decremental) are upper D and lower D respectively.


# import numpy as np

# np.eye(6,k=5)


In [172]:
#Question 2: Create an array of 8 zeros using np.zeros()

# import numpy as np

# np.zeros((8,),dtype=int)  #Shape: 8 or (8,)

# import numpy as np 

# np.zeros((2,2))

# import numpy as np 

# np.zeros((10,5),dtype=[('a','b')])  #Custom Datatype

array([[(0,), (0,), (0,), (0,), (0,)],
       [(0,), (0,), (0,), (0,), (0,)],
       [(0,), (0,), (0,), (0,), (0,)],
       [(0,), (0,), (0,), (0,), (0,)],
       [(0,), (0,), (0,), (0,), (0,)],
       [(0,), (0,), (0,), (0,), (0,)],
       [(0,), (0,), (0,), (0,), (0,)],
       [(0,), (0,), (0,), (0,), (0,)],
       [(0,), (0,), (0,), (0,), (0,)],
       [(0,), (0,), (0,), (0,), (0,)]], dtype=[('a', 'i1')])

In [182]:
#Question 3: Create an array of 6 ones using np.ones()

# import numpy as np 

# np.ones((6,),dtype=int) 

# import numpy as np

# a=(5,3)

# np.ones(a,dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [200]:
#Question 4: Create an array with values from 0 to 15 using np.arange()

# import numpy as np

# np.arange(16)

# import numpy as np

# np.arange(5,101,5)


#Step as float

# import numpy as np

# np.arange(1,10.25,0.25)

In [228]:
#Question 5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()


# import numpy as np 

# arr1=np.linspace(0,100,num=8)  #Here endpoint By default=True

# print(arr1)


# import numpy as np 

# arr1=np.linspace(0,100,num=8,endpoint=True)

# print(arr1)


# import numpy as np 

# arr2=np.linspace(0,100,num=8,endpoint=False)

# print(arr2)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]
[ 0.  12.5 25.  37.5 50.  62.5 75.  87.5]


Array Attributes and Information

In [272]:
#Question 6: What is the shape of the banking_data array?

#The attributes of the ndarray banking_data:

# Customer ID
# Account Balance ($)
# Credit Score (300-900 range)
# Transaction Count (monthly)
# Years Active (customer tenure)

# import numpy as np

# arr=[[1,586,659,12,3],    #Nested List
# [2,3777,328,43,4],
# [3,1866,760,9,3],
# [4,9730,711,49,25],
# [5,4193,534,31,2],
# [6,3388,762,32,19],
# [7,8444,814,39,10],
# [8,9992,364,12,11],
# [9,3048,832,9,21],
# [10,2295,521,15,21]]

# banking_data= np.array(arr)  #Converting nested list to ndarray

# print(banking_data,"\n")  

# print("The shape of the banking_data:",banking_data.shape) #Its a 2-D ndarray


#3-D ndarray

# import numpy as np

# arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

# print("The Shape of the 3-D ndarray is:",arr.shape)


The Shape of the 3-D ndarray is: (2, 2, 2)


In [326]:
#Question 7: What is the data type of the banking_data array?

# print("The datatype of the banking_data is:",banking_data.dtype)



#Unicode Strings

# import numpy as np

# arr=np.array(["Tony","Charles","Dustin","Justin"])

# print("The datatype of the ndarray containing the string literals:",arr.dtype)

#Another method

#By using Array function

# import numpy as np

# arr = np.array([1, 2, 3, 4], dtype='i4')  

# 32-bit integer datatype ('i4')
# 64-bit integers ('i8')
# 32-bit floating-point ('f4')


# print("The ndarray:",arr)

# print("The datatype of the ndarray arr:",arr.dtype)

The ndarray: [1 2 3 4]
The datatype of the ndarray arr: int32


In [292]:
#Question 8: What is the size (total number of elements) of the banking_data array?

#Size of the Ndarray: This attribute gives the number of the elements present in the Numpy array.

# import numpy as np

# x=np.array(banking_data)

# print("Size of the Array: ",x.size)

Size of the Array:  50


In [282]:
#Question 9: What is the number of dimensions of the banking_data array?

# print("The Number of dimensions of the banking_data:",banking_data.ndim)

#By using ndim: We can specify the number of dimensions while creating the ndarray.

# import numpy as npy

# arr = npy.array([2, 4, 6, 8, 10], ndmin=6)  #Creating an array of 6 dimension using ndim

# print(arr)

# print(arr.shape)


[[[[[[ 2  4  6  8 10]]]]]]
(1, 1, 1, 1, 1, 5)


In [258]:
#Question 10: What is the memory size of the banking_data array in bytes?

#Size: This attribute gives the number of the elements present in the Numpy array.

# import numpy as np

# x=np.array(banking_data)

# print("Size of the Array: ",x.size)

# print("Memory size of one array element in bytes: ",x.itemsize)

#Itemsize: This attribute gives the memory size of numpy array in bytes

# print("Memory size of numpy array in bytes:",x.size * x.itemsize)   # Memory= Size * Itemsize = 50*8 = 400

#Another Method

#nbytes: This attribute gives the total bytes consumed by the elements of the NumPy array.

# print("The total bytes consumed by the banking_data: ",x.nbytes)

The total bytes consumed by the banking_data:  400


Indexing and Slicing

In [380]:
#Question 11: Extract the first row of banking_data

#The attributes of the ndarray banking_data:

# Customer ID
# Account Balance ($)
# Credit Score (300-900 range)
# Transaction Count (monthly)
# Years Active (customer tenure)

import numpy as np

arr=[[1,586,659,12,3],    #Nested List
[2,3777,328,43,4],
[3,1866,760,9,3],
[4,9730,711,49,25],
[5,4193,534,31,2],
[6,3388,762,32,19],
[7,8444,814,39,10],
[8,9992,364,12,11],
[9,3048,832,9,21],
[10,2295,521,15,21]]

banking_data= np.array(arr)  #Converting nested list to ndarray

print(banking_data,"\n") 

# print("The first row of banking_data:",banking_data[0:1,0:])

[[   1  586  659   12    3]
 [   2 3777  328   43    4]
 [   3 1866  760    9    3]
 [   4 9730  711   49   25]
 [   5 4193  534   31    2]
 [   6 3388  762   32   19]
 [   7 8444  814   39   10]
 [   8 9992  364   12   11]
 [   9 3048  832    9   21]
 [  10 2295  521   15   21]] 

The first row of banking_data: [[  1 586 659  12   3]]


In [384]:
#Question 12: Extract the last row of banking_data

# print("The last row of banking_data:",banking_data[9:10,0:])

The last row of banking_data: [[  10 2295  521   15   21]]


In [402]:
#Question 13: Extract the Account_Balance column (column index 1)

# print("The Account_Balance column of the banking_data:",banking_data[0:,1:2])

The Account_Balance column of the banking_data: [[ 586]
 [3777]
 [1866]
 [9730]
 [4193]
 [3388]
 [8444]
 [9992]
 [3048]
 [2295]]


In [406]:
#Question 14: Extract the first 4 rows and first 3 columns

# print("The first 4 rows and first 3 columns of the banking_data:",banking_data[0:4,0:3])

The first 4 rows and first 3 columns of the banking_data: [[   1  586  659]
 [   2 3777  328]
 [   3 1866  760]
 [   4 9730  711]]


In [412]:
#Question 15: Extract rows 3 to 7 (inclusive)

# print("The rows 3 to 7 (inclusive) of the banking_data:",banking_data[2:7,0:])

The rows 3 to 7 (inclusive) of the banking_data: [[   3 1866  760    9    3]
 [   4 9730  711   49   25]
 [   5 4193  534   31    2]
 [   6 3388  762   32   19]
 [   7 8444  814   39   10]]


Mathematical Operations

In [370]:
#Question 16: Calculate the sum of all account balances

#The attributes of the ndarray banking_data:

# Customer ID
# Account Balance ($)
# Credit Score (300-900 range)
# Transaction Count (monthly)
# Years Active (customer tenure)

# import numpy as np

# arr=[[1,586,659,12,3],    #Nested List
# [2,3777,328,43,4],
# [3,1866,760,9,3],
# [4,9730,711,49,25],
# [5,4193,534,31,2],
# [6,3388,762,32,19],
# [7,8444,814,39,10],
# [8,9992,364,12,11],
# [9,3048,832,9,21],
# [10,2295,521,15,21]]

# banking_data= np.array(arr)  #Converting nested list to ndarray

# print(banking_data,"\n")  


# print(f"The Sum of the all account balances: {sum(banking_data[0:,1:2])}")



# import numpy as np

# np.sum([[0,1],[0,5]])

# np.sum([[0,1],[0,5]],axis=0)  #-0: it also works

# np.sum([[0,1],[0,5]],axis=-1)  #1

array([1, 5])

In [310]:
#Question 17: Calculate the mean account balance

print(f"The mean account balance: {banking_data.mean()}")

The mean account balance: 1080.58


In [316]:
#Question 18: Calculate the standard deviation of account balances

print(f"The standard deviation of account balances: {banking_data.std()}")

The standard deviation of account balances: 2338.376069754393


In [318]:
#Question 19: Calculate the variance of account balances

print(f"The variance of account balances: {banking_data.var()}")

The variance of account balances: 5468002.643600001


In [324]:
#Question 20: Calculate the median account balance

# print(f"The median account balance: {banking_data.median}")

Statistical Functions

In [454]:
#Question 21: Find the minimum and maximum account balances

#The attributes of the ndarray banking_data:

# Customer ID
# Account Balance ($)
# Credit Score (300-900 range)
# Transaction Count (monthly)
# Years Active (customer tenure)

# import numpy as np

# arr=[[1,586,659,12,3],    #Nested List
# [2,3777,328,43,4],
# [3,1866,760,9,3],
# [4,9730,711,49,25],
# [5,4193,534,31,2],
# [6,3388,762,32,19],
# [7,8444,814,39,10],
# [8,9992,364,12,11],
# [9,3048,832,9,21],
# [10,2295,521,15,21]]

# banking_data= np.array(arr)  #Converting nested list to ndarray

# print(banking_data,"\n")

x=banking_data[0:11,1:11]

print(np.min(x))

# print(f"The minimum account balance: {np.min(banking_data[:,0:2])}")

# print(f"The maximum account balance: {np.max(banking_data[:,0:2])}")

3


In [456]:
#Question 22: Find the minimum and maximum credit scores

# print(f"The minimum credit scores: {np.min(banking_data[:,2:3]}")

# print(f"The maximum credit scores: {np.min(banking_data[:,2:3]}")

In [ ]:
#Question 23: Calculate the percentile values for account balances (25th, 50th, 75th)

In [ ]:
#Question 24: Calculate the correlation between account balance and credit score

In [ ]:
#Question 25: Calculate the covariance between account balance and credit score

Array Reshaping and Manipulation

In [13]:
#Question 26: Reshape the banking_data to 5 rows × 10 columns

#The attributes of the ndarray banking_data:

# Customer ID
# Account Balance ($)
# Credit Score (300-900 range)
# Transaction Count (monthly)
# Years Active (customer tenure)

import numpy as np

arr=[[1,586,659,12,3],    #Nested List
[2,3777,328,43,4],
[3,1866,760,9,3],
[4,9730,711,49,25],
[5,4193,534,31,2],
[6,3388,762,32,19],
[7,8444,814,39,10],
[8,9992,364,12,11],
[9,3048,832,9,21],
[10,2295,521,15,21]]

banking_data= np.array(arr)  #Converting nested list to ndarray

# print(banking_data,"\n")

a=banking_data.reshape((5,10))

print(a)

[[   1  586  659   12    3    2 3777  328   43    4]
 [   3 1866  760    9    3    4 9730  711   49   25]
 [   5 4193  534   31    2    6 3388  762   32   19]
 [   7 8444  814   39   10    8 9992  364   12   11]
 [   9 3048  832    9   21   10 2295  521   15   21]]


In [19]:
#Question 27: Flatten the banking_data to a 1D array

print(banking_data.ravel())

[   1  586  659   12    3    2 3777  328   43    4    3 1866  760    9
    3    4 9730  711   49   25    5 4193  534   31    2    6 3388  762
   32   19    7 8444  814   39   10    8 9992  364   12   11    9 3048
  832    9   21   10 2295  521   15   21]


In [556]:
#Question 28: Transpose the banking_data

# print("The transpose of banking_data ndarray: ",banking_data.T)

The transpose of banking_data ndarray:  [[   1    2    3    4    2    6    7    8    9   10]
 [   3    4    3   25    5   19   10   11    9   15]
 [  12   43    9   49   31   32   39   12   21   21]
 [ 586  328  760  711  534  762  814  364  832  521]
 [ 659 3777 1866 9730 4193 3388 8444 9992 3048 2295]]


In [51]:
#Question 29: Split the banking_data into 2 equal parts vertically

# print(np.hsplit(banking_data,2))   #ValueError: array split does not result in an equal division 
                                    #Its not work with Split,hsplit,vsplit....


print(np.array_split(banking_data,2,axis=0))


[array([[   1,  586,  659,   12,    3],
       [   2, 3777,  328,   43,    4],
       [   3, 1866,  760,    9,    3],
       [   4, 9730,  711,   49,   25],
       [   5, 4193,  534,   31,    2]]), array([[   6, 3388,  762,   32,   19],
       [   7, 8444,  814,   39,   10],
       [   8, 9992,  364,   12,   11],
       [   9, 3048,  832,    9,   21],
       [  10, 2295,  521,   15,   21]])]


In [53]:
#Question 30: Split the banking_data into 2 equal parts horizontally


print(np.array_split(banking_data,2,axis=1))

[array([[   1,  586,  659],
       [   2, 3777,  328],
       [   3, 1866,  760],
       [   4, 9730,  711],
       [   5, 4193,  534],
       [   6, 3388,  762],
       [   7, 8444,  814],
       [   8, 9992,  364],
       [   9, 3048,  832],
       [  10, 2295,  521]]), array([[12,  3],
       [43,  4],
       [ 9,  3],
       [49, 25],
       [31,  2],
       [32, 19],
       [39, 10],
       [12, 11],
       [ 9, 21],
       [15, 21]])]


Logical Operations and Filtering

In [558]:
#Question 31: Find customers with account balance greater than $100,000

print("the customers with account balance greater than $100,000:",np.sort(banking_data[0:,1:2]>100000))

the customers with account balance greater than $100,000: [[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]]


In [ ]:
#Question 32: Find customers with credit score greater than 800

print("the customers with credit score greater than 800:",np.sort(banking_data[0:,1:2]>100000))

In [ ]:
#Question 33: Find customers with transaction count greater than 50 AND credit score less than 750

In [ ]:
#Question 34: Count how many customers have account balance between $10,000 and $100,000

In [ ]:
#Question 35: Find the index of the customer with the highest credit score

Sorting and Searching

In [590]:
#Question 36: Sort the banking_data by account balance (ascending)

#The attributes of the ndarray banking_data:

# Customer ID
# Account Balance ($)
# Credit Score (300-900 range)
# Transaction Count (monthly)
# Years Active (customer tenure)

# import numpy as np

arr=[[1,586,659,12,3],    #Nested List
    [2,3777,328,43,4],
    [3,1866,760,9,3],
    [4,9730,711,49,25],
    [5,4193,534,31,2],
    [6,3388,762,32,19],
    [7,8444,814,39,10],
    [8,9992,364,12,11],
    [9,3048,832,9,21],
    [10,2295,521,15,21]]

# banking_data= np.array(arr)  #Converting nested list to ndarray

# print(banking_data,"\n")

print("the Sorting the banking_data by account balance (ascending):",np.sort(banking_data[0:,1]))

the Sorting the banking_data by account balance (ascending): [ 3  3  4  5  9 10 11 15 19 25]


In [566]:
#Question 37: Sort the banking_data by credit score (descending)

print("the Sorting the banking_data by account balance (descending):",np.sort(banking_data[:,2:3]))

the Sorting the banking_data by account balance (descending): [[12]
 [43]
 [ 9]
 [49]
 [31]
 [32]
 [39]
 [12]
 [21]
 [21]]


In [ ]:
#Question 38: Find the indices that would sort the array by years active

In [ ]:
#Question 39: Find the customer with the second highest account balance

In [560]:
#Question 40: Find the customer with the lowest transaction count

print("the customers with credit score greater than 800:",np.sort(banking_data[0:,1:2]))

the customers with credit score greater than 800: [[ 3]
 [ 4]
 [ 3]
 [25]
 [ 5]
 [19]
 [10]
 [11]
 [ 9]
 [15]]


Mathematical Functions

In [ ]:
#Question 41: Calculate the absolute values of all elements

In [ ]:
#Question 42: Calculate the square root of all account balances

In [ ]:
#Question 43: Calculate the square of all credit scores

In [ ]:
#Question 44: Calculate the exponential of all transaction counts

In [ ]:
#Question 45: Calculate the natural logarithm of all account balances

Advanced Operations

In [ ]:
#Question 46: Calculate the cumulative sum of account balances

In [ ]:
#Question 47: Calculate the cumulative product of transaction counts

In [ ]:
#Question 48: Calculate the difference between consecutive account balances

In [ ]:
#Question 49: Calculate the gradient of account balances

In [65]:
#Question 50: Calculate the histogram of account balances with 5 bins

Random Numbers and Simulation

In [119]:
#Question 51: Generate 6 random integers between 1 and 1000

import numpy as np

a=np.random.randint(1,1000,6)

a

array([831, 874, 904, 317, 944, 705], dtype=int32)

In [135]:
#Question 52: Generate 6 random floats between 0 and 1

import numpy as np

b=np.random.random([0,1])
b

array([], shape=(0, 1), dtype=float64)

In [ ]:
#Question 53: Generate 6 random numbers from normal distribution (mean=700, std=100)

In [ ]:
#Question 54: Shuffle the banking_data rows randomly

In [ ]:
#Question 55: Set random seed to 123 and generate 4 random numbers

Linear Algebra Operations

In [ ]:
#Question 56: Calculate the dot product of account balance and credit score columns

In [ ]:
#Question 57: Calculate the cross product of first two rows

In [ ]:
#Question 58: Calculate the norm (magnitude) of the account balance column

In [ ]:
#Question 59: Create a 3x3 matrix and calculate its determinant

In [ ]:
#Question 60: Calculate the inverse of the 3x3 matrix

String Operations

In [ ]:
#Question 61: Convert all customer IDs to strings

In [ ]:
#Question 62: Check if any customer ID contains '100'

In [ ]:
#Question 63: Convert all customer IDs to uppercase (if they were strings)

In [ ]:
#Question 64: Count the length of each customer ID string

In [ ]:
#Question 65: Replace '100' with 'CUST' in customer IDs

Date and Time Operations

In [ ]:
#Question 66: Convert years active to months

In [84]:
#Question 67: Calculate the average years active

In [ ]:
#Question 68: Find customers who have been active for more than 5 years

In [ ]:
#Question 69: Calculate the total time all customers have been active (in years)

In [ ]:
#Question 70: Find the customer with the shortest time active

Advanced Array Operations

In [ ]:
#Question 71: Apply a function to calculate 5% interest on all account balances

In [90]:
#Question 72: Use np.where to categorize customers by balance ranges

In [92]:
#Question 73: Use np.select to categorize customers by credit score ranges

In [ ]:
#Question 74: Use np.piecewise to apply different interest rates based on balance

In [ ]:
#Question 75: Use np.apply_along_axis to calculate the sum of each row

Array Concatenation and Stacking

In [554]:
#Question 76: Concatenate two arrays horizontally using np.hstack()

# import numpy as np

# a=np.array([5,2])

# b=np.array([7,2])

# a = np.array([[1, 2], [3, 4]])

# b = np.array([[5, 6]])
# np.concatenate((a, b), axis=0)
# print("Concatenate two arrays horizontally:",np.concatenate((a,b),axis=1)

In [ ]:
#Question 77: Concatenate two arrays vertically using np.vstack()

In [ ]:
#Question 78: Concatenate arrays along a specific axis using np.concatenate()

In [ ]:
#Question 79: Stack arrays depth-wise using np.dstack()

In [ ]:
#Question 80: Create a column stack using np.column_stack()

Array Splitting Operations

In [67]:
#Question 81: Split an array into 3 equal parts using np.split()

# import numpy as np

# a=np.random.randint(0,100,(6,8))

# print("The Original ndarray a:",a,"\n")

# print("The Original ndarray a divided into 3 equal parts:",np.split(a,3))

The Original ndarray a: [[81  8 93 81 43 43 38 60]
 [58 83 58 93 36 60 51 61]
 [41 43 34 59 55  8 92 30]
 [87 42  5  6 23 21  8 21]
 [57 14  9 72 24  7  1 88]
 [82 68 31 74 79 16 81 45]] 

The Original ndarray a divided into 3 equal parts: [array([[81,  8, 93, 81, 43, 43, 38, 60],
       [58, 83, 58, 93, 36, 60, 51, 61]], dtype=int32), array([[41, 43, 34, 59, 55,  8, 92, 30],
       [87, 42,  5,  6, 23, 21,  8, 21]], dtype=int32), array([[57, 14,  9, 72, 24,  7,  1, 88],
       [82, 68, 31, 74, 79, 16, 81, 45]], dtype=int32)]


In [77]:
#Question 82: Split an array at specific indices using np.split()
x=a[4:,0:6]  #TypeError: only integer scalar arrays can be converted to a scalar index

# print("The Original ndarray a divided into 3 equal parts:",np.split(a,x))

In [107]:
#Question 83: Split an array horizontally using np.hsplit()

# print("The Original ndarray a divided into 3 equal parts horizontally:",np.hsplit(a,3))

#Since its a hsplit,raises an error
#ValueError: array split does not result in an equal division


# print("The Original ndarray a divided into 4 equal parts horizontally:",np.hsplit(a,2))

In [91]:
#Question 84: Split an array vertically using np.vsplit()

# print("The Original ndarray a divided into 3 equal parts horizontally:",np.vsplit(a,3)) 

The Original ndarray a divided into 3 equal parts horizontally: [array([[81,  8, 93, 81, 43, 43, 38, 60],
       [58, 83, 58, 93, 36, 60, 51, 61]], dtype=int32), array([[41, 43, 34, 59, 55,  8, 92, 30],
       [87, 42,  5,  6, 23, 21,  8, 21]], dtype=int32), array([[57, 14,  9, 72, 24,  7,  1, 88],
       [82, 68, 31, 74, 79, 16, 81, 45]], dtype=int32)]


In [113]:
#Question 85: Split an array into equal chunks using np.array_split()

#Array_split: It doesnt raise any errors while splitting odd column numbers.

print("The Original ndarray 'a' divided into 2 equal parts:",np.array_split(a,2,axis=0))

print("The Original ndarray 'a' divided into 2 equal parts:",np.array_split(a,2,axis=1))

The Original ndarray a divided into 2 equal parts: [array([[81,  8, 93, 81, 43, 43, 38, 60],
       [58, 83, 58, 93, 36, 60, 51, 61],
       [41, 43, 34, 59, 55,  8, 92, 30]], dtype=int32), array([[87, 42,  5,  6, 23, 21,  8, 21],
       [57, 14,  9, 72, 24,  7,  1, 88],
       [82, 68, 31, 74, 79, 16, 81, 45]], dtype=int32)]
The Original ndarray a divided into 2 equal parts: [array([[81,  8, 93, 81],
       [58, 83, 58, 93],
       [41, 43, 34, 59],
       [87, 42,  5,  6],
       [57, 14,  9, 72],
       [82, 68, 31, 74]], dtype=int32), array([[43, 43, 38, 60],
       [36, 60, 51, 61],
       [55,  8, 92, 30],
       [23, 21,  8, 21],
       [24,  7,  1, 88],
       [79, 16, 81, 45]], dtype=int32)]


Array Repetition and Tiling

In [112]:
#Question 86: Repeat each element of an array 3 times using np.repeat()

In [ ]:
#Question 87: Repeat an entire array 2 times using np.tile()

In [ ]:
#Question 88: Repeat a 2D array using np.tile()

In [ ]:
#Question 89: Create a pattern using np.tile()

In [ ]:
#Question 90: Repeat elements with different counts using np.repeat()

Array Comparison and Logical Operations

In [478]:
#Question 91: Compare two arrays for equality using np.array_equal()

# import numpy as np

# a=np.array([1,2,3])        #Rank=1

# b=np.array([1,2,3,4])

# c=np.array([[1,2],[3,4]])  #Rank=2

# d=np.array([1,2,3])

# print("The first ndarray a:",a)
# print("The Second ndarray b:",b,"\n")

# print("Checking the equality for a and b:",np.array_equal(a,b))

# print("Checking the equality for b and c:",np.array_equal(b,c),"\n")

# print("Checking the equality for a and d:",np.array_equal(a,d))

The first ndarray a: [1 2 3]
The Second ndarray b: [1 2 3 4] 

Checking the equality for a and b: False
Checking the equality for b and c: False 

Checking the equality for a and d: True


In [482]:
#Question 92: Check if arrays are close using np.allclose()

# import numpy as np

# a=np.array([1,2,3])        #Rank=1

# b=np.array([1,2,3,4])

# # c=np.array([[1,2],[3,4]])  #Rank=2

# # d=np.array([1,2,3])

# print("The first ndarray a:",a)
# print("The Second ndarray b:",b,"\n")

# print("Checking the equality for a and b:",np.allclose(a,b))


In [506]:
#Question 93: Apply logical AND operation between arrays

# import numpy as np

# a=np.array([1,8,6])        #Rank=1

# b=np.array([2,2,6])

# print("Applying the logical_and between a and b ndarrays:",np.logical_and(a,b))

# c=np.array([1,2])

# print("Applying the logical_and between a and b ndarrays:",np.logical_and(a,c)) 

#ValueError: operands could not be broadcast together with shapes (3,) (2,)



# d=np.array([[1,2],[3,4]])   #Rank=2

# e=np.array([[0,2],[2,3]])

# print("Applying the logical_and between a and b ndarrays:",np.logical_and(d,e))

Applying the logical_and between a and b ndarrays: [ True  True  True]


In [520]:
#Question 94: Apply logical OR operation between arrays

# import numpy as np

# a=np.array([1,8,6,0])        #Rank=1

# b=np.array([2,2,6,7])

# print("Applying the logical_or between a and b ndarrays:",np.logical_or(a,b))

# c=np.array([1,2])

# print("Applying the logical_or between a and b ndarrays:",np.logical_or(a,c)) 

#ValueError: operands could not be broadcast together with shapes (3,) (2,)



# d=np.array([[1,2],[3,4]])   #Rank=2

# e=np.array([[0,2],[2,3]])

# print("Applying the logical_or between a and b ndarrays:",np.logical_and(d,e))

Applying the logical_or between a and b ndarrays: [[False  True]
 [ True  True]]


In [534]:
#Question 95: Apply logical NOT operation to an array

# import numpy as np

# a=np.array([1,8,6,0,True])        #Rank=1

# b=np.array([2,2,6,7,False])

# print("Applying the logical_or between a and b ndarrays:",np.logical_not(a),"\n")

# print("Applying the logical_or between a and b ndarrays:",np.logical_not(b))

Applying the logical_or between a and b ndarrays: [False False False  True False] 

Applying the logical_or between a and b ndarrays: [False False False False  True]


Array Set Operations

In [ ]:
#Question 96: Find unique elements in an array using np.unique()

In [ ]:
#Question 97: Find the intersection of two arrays using np.intersect1d()

In [ ]:
#Question 98: Find the union of two arrays using np.union1d()

In [ ]:
#Question 99: Find elements in first array but not in second using np.setdiff1d()

In [ ]:
#Question 100: Find the symmetric difference between two arrays using np.setxor1d()

THE END