In [9]:
#Numpy

# import numpy as np

# arr=np.array([1,2,3])    #Rank=1

# print(arr)

# arr=np.array([[2,4,6],   #Rank=2
#              [8,10,12]])   #If you miss "[]" or "()":TypeError: Field elements must be 2- or 3-tuples, got '8' 

# print(arr)

[1 2 3]
[[ 2  4  6]
 [ 8 10 12]]


In [15]:
#Numpy Indexing

#Accessing all the elements by index

# import numpy as np

# arr=np.array([[-2,6,8],       #Rank=2
#               [-9,1.5,7]])
# print(arr)

# print(arr[0,0])  #arr[Rows,Columns]
# print(arr[0,1])
# print(arr[0,2])
# print(arr[1,0])
# print(arr[1,1])
# print(arr[1,2])  

# print(arr[0:1]) #First Row

# print(arr[1:2]) #Second Row

# import numpy as np

# arr = np.array([[-1, 2, 0, 4],
#                 [4, -0.5, 6, 0],
#                 [2.6, 0, 7, 8],
#                 [3, -7, 4, 2.0]])

# Second Column
# print(*arr[0:,1])

# Fourth Column
# print(*arr[0:,3])

# Third row
# print(*arr[2:3,0:])

# Fourth Row
# print(*arr[3,0:4])


3.0 -7.0 4.0 2.0


In [21]:
# import numpy as np

# data=np.random.randint(0,50,(4,4))

# data


array([[19, 10,  1,  3],
       [ 4, 25, 23, 17],
       [13, 15, 39, 46],
       [22, 24, 13, 41]], dtype=int32)

In [1]:
# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]

# import numpy as np

# retail_data = np.array([
#     [1, 25000, 300, 1200, 10],
#     [2, 32000, 450, 1500, 15],
#     [3, 28000, 380, 1100, 8],
#     [4, 41000, 500, 1600, 20],
#     [5, 35000, 420, 1400, 12],
#     [6, 27000, 360, 1300, 9],
#     [7, 39000, 480, 1700, 18],
#     [8, 30000, 400, 1250, 14],
#     [9, 45000, 550, 1800, 25],
#     [10, 33000, 410, 1450, 11]
# ])

# print(retail_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


Basic Performance Analysis

In [26]:
# Retail Data – Business Questions (for `retail_data`)

# **Assumed columns:** `[StoreID, Sales, Customers, Inventory, Returns]`

## Basic Performance Analysis

# Question 1. What is the **total revenue** generated across all stores?
# tot_rev = retail_data[:,1].sum() * retail_data[:,3].sum()
# tot_rev

# print(f"the total revenue generated across all stores is: {tot_rev}")

the total revenue generated across all stores is: 4790500000


In [28]:
# Question 2. Which store recorded the **highest sales**?
# a=retail_data[:,1].argmax()+1   # +1: Index starts at 0

# print(f"the store recorded the highest sales is Store id: {a}")

the store recorded the highest sales is Store id: 9


In [32]:
# Question 3. Which store recorded the **lowest sales**?
# b=retail_data[:,1].argmin()+1   # +1: Index starts at 0

# print(f"the store recorded the lowest sales is Store id: {b}")

the store recorded the lowest sales is Store id: 1


In [34]:
# Question 4. What is the **average daily sales** per store?
# c=retail_data[:,1].sum() / 10

# print(f"the average daily sales per store: {c}")

the average daily sales per store: 33500.0


In [52]:
# Question 5. How many stores achieved sales **above ₹35,000**?

# data = (retail_data[:,1])
# x=data[data > 35000]

# print(f"The stores achieved sales above ₹35,000: {x}")

The stores achieved sales above ₹35,000: [41000 39000 45000]


Customer Insights

In [57]:
# Customer Insights
# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]

# import numpy as np

# retail_data = np.array([
#     [1, 25000, 300, 1200, 10],
#     [2, 32000, 450, 1500, 15],
#     [3, 28000, 380, 1100, 8],
#     [4, 41000, 500, 1600, 20],
#     [5, 35000, 420, 1400, 12],
#     [6, 27000, 360, 1300, 9],
#     [7, 39000, 480, 1700, 18],
#     [8, 30000, 400, 1250, 14],
#     [9, 45000, 550, 1800, 25],
#     [10, 33000, 410, 1450, 11]
# ])


# Question 6. Which store had the **highest customer footfall**?
# a=retail_data[:,2].argmax()+1

# print(f"The stores achieved sales above ₹35,000: {a}")

The stores achieved sales above ₹35,000: 9


In [61]:
# Question 7. What is the **average number of customers** per store?
# b=retail_data[:,2].mean()

# print(f"The average number of customers per store: {b}")

The average number of customers per store: 425.0


In [66]:
# Question 8. How many stores have **more than 450 customers**?
# dat = retail_data[:,2]
# x=dat[dat>450]

# print(f"The stores have more than 450 customers are: {x}")

The stores have more than 450 customers are: [500 480 550]


In [68]:
# Question 9. Which store has the **lowest customer count**?
# y=retail_data[:,2].argmin()+1

# print(f"The store has the lowest customer count: {y}")

The store has the lowest customer count: 1


In [70]:
# Question 10. Is there any store where **high sales do not correspond to high customers**?
# sales = retail_data[:,1].mean()
# customers = retail_data[:,2].mean()

# z= retail_data[(retail_data[:,1] > sales) & (retail_data[:,2] < customers)]

# print(f"A store where high sales do not correspond to high customers: {z}")

A store where high sales do not correspond to high customers: [[    5 35000   420  1400    12]]


Inventory & Returns Analysis

In [72]:
# Inventory & Returns Analysis
# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]

# import numpy as np

# retail_data = np.array([
#     [1, 25000, 300, 1200, 10],
#     [2, 32000, 450, 1500, 15],
#     [3, 28000, 380, 1100, 8],
#     [4, 41000, 500, 1600, 20],
#     [5, 35000, 420, 1400, 12],
#     [6, 27000, 360, 1300, 9],
#     [7, 39000, 480, 1700, 18],
#     [8, 30000, 400, 1250, 14],
#     [9, 45000, 550, 1800, 25],
#     [10, 33000, 410, 1450, 11]
# ])

# Question 11. What is the **total inventory** across all stores?
# a=retail_data[:,3].sum()

# print(f"The total inventory across all stores: {a}")

The total inventory across all stores: 14300


In [74]:
# Question 12. Which store has the **highest inventory stock**?
# b=retail_data[:,3].argmax()+1

# print(f"A store has the highest inventory stock: {b}")

A store has the highest inventory stock: 9


In [76]:
# Question 13. How many stores have **inventory less than 1300 units**?
# lowest_inve = retail_data[(retail_data[:,3]) < 1300]

# print(f"A stores have inventory less than 1300 units: {lowest_inve}")

A stores have inventory less than 1300 units: [[    1 25000   300  1200    10]
 [    3 28000   380  1100     8]
 [    8 30000   400  1250    14]]


In [78]:
# Question 14. Which store has the **highest return rate** (returns ÷ inventory)?
# ret_rate = (retail_data[:,4]) / (retail_data[:,3])
# x=ret_rate.argmax()+1

# print(f"A store has the highest return rate: {x}")

A store has the highest return rate: 9


In [80]:
# Question 15. Which stores have **returns greater than 15 units**?
# returns = retail_data[(retail_data[:,4]) > 15]

# print(f"A stores have returns greater than 15 units: {returns}")

A stores have returns greater than 15 units: [[    4 41000   500  1600    20]
 [    7 39000   480  1700    18]
 [    9 45000   550  1800    25]]


Sales & Customer Correlation

In [ ]:
# Sales & Customer Correlation
# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]

import numpy as np

retail_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

# Question 16. Is there a **positive correlation** between sales and customers?

# print(f"Is there a positive correlation between sales and customers: {}")

In [86]:
# Question 17. Which store has **high customer visits but low sales**?
first = retail_data[:,2].mean()
sec = retail_data[:,1].mean()
res = retail_data[(retail_data[:,2] > first) & (retail_data[:,1] < sec)]
res

print(f"A store has high customer visits but low sales: {res}")

A store has high customer visits but low sales: [[    2 32000   450  1500    15]]


In [92]:
# Question 18. Which store has **low customers but high sales**?
p= retail_data[:,2].mean()
q = retail_data[:,1].mean()
r = retail_data[(retail_data[:,2] < first) & (retail_data[:,1] > sec)]
r

print(f"A store has high customer visits but low sales: {r}")

A store has high customer visits but low sales: [[    5 35000   420  1400    12]]


In [90]:
# Question 19. How many stores have **sales per customer above ₹90**?
a = retail_data[:,1] / retail_data[:,2]
b = np.sum(res > 90)

print(f"A stores have sales per customer above ₹90: {b}")

A stores have sales per customer above ₹90: 3


In [96]:
# Question 20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?


Profitability & Growth

In [100]:
# Profitability & Growth
# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]

import numpy as np

retail_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

# Question 21. If profit margin is **20% of sales**, what is the **profit per store**?
pps= 0.20 * retail_data[:,1]

print(f"The profit per store for all stores: {pps}")

The profit per store for all stores: [5000. 6400. 5600. 8200. 7000. 5400. 7800. 6000. 9000. 6600.]


In [104]:
# Question 22. Which store has the **highest profit**?
highest_profit =(retail_data[:,1] * 0.20).argmax()+1

print(f"The store has the highest profit with store id: {highest_profit}")

The store has the highest profit with store id: 9


In [108]:
# Question 23. Which store has the **lowest profit**?
lowest_profit= (retail_data[:,1] * 0.20).argmin()+1

print(f"The store has the lowest profit with store id: {lowest_profit}")

The store has the lowest profit with store id: 1


In [110]:
# Question 24. If sales increase by **10% next month**, what are the **new sales figures**?
x=retail_data[:,1] * 0.10

print(f"The new sales figures for all stores: {x}")

The new sales figures for all stores: [2500. 3200. 2800. 4100. 3500. 2700. 3900. 3000. 4500. 3300.]


In [112]:
# Question 25. How will **total profit** change with the 10% sales increase?
z=(retail_data[:,1] * 0.10) + retail_data[:,1]

print(f"The total profit change with the 10% sales increase: {z}")

The total profit change with the 10% sales increase: [27500. 35200. 30800. 45100. 38500. 29700. 42900. 33000. 49500. 36300.]


In [116]:
# Operational Strategy
# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]

import numpy as np

retail_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

# Question 26. Which stores need **inventory restocking** based on sales and current stock?
sales = retail_data[:,1].mean()
inventory = retail_data[:,4].mean()
re_stock = retail_data[(retail_data[:,1] > sales) & (retail_data[:,4] < inventory)]

print(f"The stores need inventory restocking based on sales and current stock: {re_stock}")

The stores need inventory restocking based on sales and current stock: [[    5 35000   420  1400    12]]


In [120]:
# Question 27. Which stores show **high returns percentage** and might require **quality checks**?
average = retail_data[:,4].mean()
res = retail_data[(retail_data[:,4] > average)]

print(f"The stores show high returns percentage and might require quality checks: {res}")

The stores show high returns percentage and might require quality checks: [[    2 32000   450  1500    15]
 [    4 41000   500  1600    20]
 [    7 39000   480  1700    18]
 [    9 45000   550  1800    25]]


In [ ]:
# Question 28. Which store is the **best performer overall** (sales, customers, inventory turnover)?
inventory_turnover = retail_data[:, 1] / retail_data[:, 4]

# Normalize metrics (min-max scaling)
sales_norm = (retail_data[:, 1] - retail_data[:, 1].min()) / (retail_data[:, 1].max() - retail_data[:, 1].min())
customers_norm = (retail_data[:, 2] - retail_data[:, 2].min()) / (retail_data[:, 2].max() - retail_data[:, 2].min())
turnover_norm = (inventory_turnover - inventory_turnover.min()) / (inventory_turnover.max() - inventory_turnover.min())

# Composite score (equal weights)
overall_score = sales_norm + customers_norm + turnover_norm

# Find best performer
best_index = np.argmax(overall_score)
best_store = retail_data[best_index]

print(f"Best performer overall: Store ID {int(best_store[0])}")
print(f"Sales: {best_store[1]}, Customers: {best_store[2]}, Inventory: {best_store[4]}")

In [ ]:
# Question 29. Which store is the **worst performer overall**?
inventory_turnover = retail_data[:, 1] / retail_data[:, 4]

# Normalize metrics (min-max scaling)
sales_norm = (retail_data[:, 1] - retail_data[:, 1].min()) / (retail_data[:, 1].max() - retail_data[:, 1].min())
customers_norm = (retail_data[:, 2] - retail_data[:, 2].min()) / (retail_data[:, 2].max() - retail_data[:, 2].min())
turnover_norm = (inventory_turnover - inventory_turnover.min()) / (inventory_turnover.max() - inventory_turnover.min())

# Composite score (equal weights)
overall_score = sales_norm + customers_norm + turnover_norm

# Find worst performer
worst_index = np.argmin(overall_score)
worst_store = retail_data[worst_index]

print(f"Worst performer overall: Store ID {int(worst_store[0])}")
print(f"Sales: {worst_store[1]}, Customers: {worst_store[2]}, Inventory: {worst_store[4]}")

In [122]:
# Question 30. Which stores can be considered for **expansion** based on strong sales and customer metrics?
a = retail_data[:,1].mean()
b = retail_data[:,2].mean()
res = retail_data[(retail_data[:,1] > a) & (retail_data[:,2] > b)]

print(f"The stores can be considered for expansion based on strong sales and customer metrics: {res}")

The stores can be considered for expansion based on strong sales and customer metrics: [[    4 41000   500  1600    20]
 [    7 39000   480  1700    18]
 [    9 45000   550  1800    25]]
